name: "kidney_sofa_example"

data:
  train: "data/kidney_sofa_example/kidney_dataset-training_nostd.rds"


features:
  - urine24
  - crea
  - artph
  - bun
  - temp
  - lactate

threshold: 0.21 #0.21


target: "target"


GAM:
  link: "identity"
  distribution: "normal"


plot: #plot limits
  ylim: -1.3, 4.3
  urine24:
    xlim: 0, 1000
    n: 1000
    n_splines: 150
  crea:
    xlim: 0.15, 5.2
    n_splines: 125
  artph:
    xlim: 7.1, 7.6
  bun:
    xlim: 0, 200
  temp:
    xlim: 34, 40
  lactate:
    xlim: 0, 15


  types:
    - circular
    - non-circular
    - all
    - decision_function

decision_function:
  0:
    crea: 0
    urine24: 500
  1:
    crea: 1.2
  2:
    crea: 1.9
  3:
    crea: 3.4
    urine24: 200
  4:
    crea: 4.9
    urine24: 0


